apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: sensor
build:
  artifacts:
  - image: zeek/zeek
    context: zeek
    docker:
      dockerfile: Dockerfile
manifests:
  kustomize:
    paths:
    - vector-deployment
profiles:
- name: zeek-deployment
  manifests:
    kustomize:
      paths:
      - zeek-deployment
