apiVersion: v1
kind: Pod
metadata:
  name: sensor
  namespace: zeek
spec:
  containers:
    - name: sensor
      image: zeek/zeek:5.1.2
      command:
        - /usr/local/zeek/bin/zeek
      args:
        - -C
        - -i
        - eth0
        - LogAscii::use_json=T
      workingDir: /usr/local/zeek/logs
      volumeMounts:
        - mountPath: /usr/local/zeek/logs
          name: zeeklogs
    - name: exporter
      image: timberio/vector:0.27.X-distroless-libc
      args:
        - --watch-config
        - --config-yaml
        - /etc/vector/vector.yaml
      env:
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: K8S_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: K8S_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: K8S_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      volumeMounts:
        - mountPath: /usr/local/zeek/logs
          name: zeeklogs
          readOnly: true
        - name: vectorstate
          mountPath: /var/lib/vector
        - name: vectorcfg
          mountPath: /etc/vector
  volumes:
    - name: zeeklogs
      emptyDir: {}
    - name: vectorstate
      emptyDir: {}
    - name: vectorcfg
      projected:
        sources:
          - configMap:
              name: vectorconfig
