apiVersion: v1
kind: Pod
metadata:
  name: tester
  namespace: zeek
spec:
  containers:
    - name: tester
      image: zeek/zeek:5.1.2
      command:
        - /bin/bash
        - -c
        - sleep inf
