---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zeek

resources:
  - namespace.yaml
  - deployment.yaml

configMapGenerator:
  - name: vector-sidecar
    files:
      - config/sidecar.yaml
